name: Terraform and Docker Compose CI

on:
  push:
    branches:
      - main

jobs:
  terraform-docker:
    runs-on: [self-hosted, linux]

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0 # Adjust to your required version

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Validate Terraform files
      - name: Terraform Validate
        run: terraform validate

      # Step 5: Plan Terraform deployment
      - name: Terraform Plan
        run: terraform plan

      # Step 6: Apply Terraform deployment
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Step 7: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 8: Start Docker Compose services
      - name: Docker Compose Up
        run: docker-compose up -d --build

      # Optional: Run tests or additional commands
      # - name: Run Tests
      #   run: |
      #     docker-compose exec <service-name> <test-command>

      # Step 9: Stop and clean up Docker Compose
      # - name: Docker Compose Down
      #   if: always()
      #   run: docker-compose down
